# Scoreboard main
<View>:
    do_default_tab: False
    tablive: tablive
    tabmaps: tabmaps
    tabcustom: tabcustom
    tabteams: tabteams

    TabbedPanelItem:
        text: "Live"
        id: tablive

    TabbedPanelItem:
        text: "Maps"
        id: tabmaps
        # Contains a MapManager, probably instantiated from save.

    TabbedPanelItem:
        text: "Text"
        id: tabcustom

    TabbedPanelItem:
        text: "Teams"
        id: tabteams
